all: Audi Kia Lexus Mazda Mercedes-Benz Opel Tesla Volkswagen Volvo

Audi:
	bash netcarshow.sh -b Audi -m "A3 Sportback S-Line" -y 2014
	bash netcarshow.sh -b Audi -m A4 -y 2008
	bash netcarshow.sh -b Audi -m A5 -y 2012
	bash netcarshow.sh -b Audi -m "A5 Sportback" -y 2010
	bash netcarshow.sh -b Audi -m "A5 Sportback" -y 2012
	bash netcarshow.sh -b Audi -m A6 -y 2012
	bash netcarshow.sh -b Audi -m "A7 Sportback" -y 2011
	bash netcarshow.sh -b Audi -m "R8 V10 plus" -y 2013
	bash netcarshow.sh -b Audi -m "RS Q3 Concept" -y 2012
	bash netcarshow.sh -b Audi -m "RS4 Avant" -y 2013
	bash netcarshow.sh -b Audi -m RS5 -y 2011
	bash netcarshow.sh -b Audi -m RS5 -y 2012
	bash netcarshow.sh -b Audi -m "RS6 Avant" -y 2014
	bash netcarshow.sh -b Audi -m S3 -y 2014
	bash netcarshow.sh -b Audi -m S4 -y 2009
	bash netcarshow.sh -b Audi -m S4 -y 2013
	bash netcarshow.sh -b Audi -m S5 -y 2012
	bash netcarshow.sh -b Audi -m "S5 Sportback" -y 2011
	bash netcarshow.sh -b Audi -m "S5 Sportback" -y 2012
	bash netcarshow.sh -b Audi -m S6 -y 2013
	bash netcarshow.sh -b Audi -m "S7 Sportback" -y 2013
	bash netcarshow.sh -b Audi -m SQ5 -y 2013

Kia:
	bash netcarshow.sh -b Kia -m Optima -y 2011

Lexus:
	bash netcarshow.sh -b Lexus -m IS -y 2014

Mazda:
	bash netcarshow.sh -b Mazda -m "6 Sedan" -y 2008
	bash netcarshow.sh -b Mazda -m "6 Sedan" -y 2013

Mercedes-Benz:
	bash netcarshow.sh -b Mercedes-Benz -m A-Class -y 2013
	bash netcarshow.sh -b Mercedes-Benz -m C-Class -y 2012
	bash netcarshow.sh -b Mercedes-Benz -m "C-Class Coupe" -y 2012
	bash netcarshow.sh -b Mercedes-Benz -m "CLS63 AMG S-Model" -y 2014
	bash netcarshow.sh -b Mercedes-Benz -m CLS-Class -y 2012
	bash netcarshow.sh -b Mercedes-Benz -m "E63 AMG" -y 2014
	bash netcarshow.sh -b Mercedes-Benz -m "E63 AMG Estate" -y 2014
	bash netcarshow.sh -b Mercedes-Benz -m E-Class -y 2014
	bash netcarshow.sh -b Mercedes-Benz -m "E-Class Coupe" -y 2014
	bash netcarshow.sh -b Mercedes-Benz -m "E-Class Estate" -y 2014
	bash netcarshow.sh -b Mercedes-Benz -m GLK-Class -y 2013
	bash netcarshow.sh -b Mercedes-Benz -m "Style Coupe Concept" -y 2012

Opel:
	bash netcarshow.sh -b Opel -m "Astra GTC" -y 2012
	bash netcarshow.sh -b Opel -m "GTC Paris Concept" -y 2010

Tesla:
	bash netcarshow.sh -b Tesla -m "Model S" -y 2013

Volkswagen:
	bash netcarshow.sh -b Volkswagen -m "Jetta EU Version" -y 2011

Volvo:
	bash netcarshow.sh -b Volvo -m "V40 R-Design" -y 2013
	bash netcarshow.sh -b Volvo -m "S60 R-Design" -y 2011
